sudo: false

language: php

branches:
    only:
        - master

matrix:
    fast_finish: true

    include:
        - php: 5.6
          env: WP_VERSION=latest PHP_LINT=1 WP_PHPCS=1
        - php: 5.6
          env: WP_VERSION=latest
        - php: 5.6
          env: WP_VERSION=latest

        - php: 7.2
          env: WP_VERSION=nightly PHP_LINT=1
        - php: 7.2
          env: WP_VERSION=latest
        - php: 7.2
          env: WP_VERSION=latest

before_script:
  # Turn off Xdebug. See https://core.trac.wordpress.org/changeset/40138.
  - phpenv config-rm xdebug.ini || echo "Xdebug not available"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Couple the PHPUnit version to the PHP version.
  - |
    case "$TRAVIS_PHP_VERSION" in
    7.2|7.0|nightly)
      echo "Using PHPUnit 6.1"
      composer global require "phpunit/phpunit=6.1.*"
      ;;
    5.6)
      echo "Using PHPUnit 4.8"
      composer global require "phpunit/phpunit=4.8.*"
      ;;
    *)
      echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
      exit 1
      ;;
    esac

    # After CodeSniffer install you should refresh your path.
    phpenv rehash

  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

      # For debugging.
      which phpunit
      phpunit --version
    fi

  # Set up phpcs.
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer global require automattic/vipwpcs
      phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs,$HOME/.composer/vendor/automattic/vipwpcs

      # After CodeSniffer install you should refresh your path.
      phpenv rehash
    fi

script:
    - |
      if [[ "$PHP_LINT" == "1" ]]; then
        find . -type "f" -iname "*.php" | xargs -L "1" php -l;
      fi

    - |
      if [[ "$WP_PHPCS" == "1" ]] ; then
        phpcs -n
      fi

    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        phpunit
        WP_MULTISITE=1 phpunit
      fi

notifications:
    email: false
