sudo: false

language: php

branches:
    only:
        - master

matrix:
    fast_finish: true

    include:
        - php: '5.3'
          env: WP_VERSION=master PHP_LINT=1
        - php: '5.3'
          env: WP_VERSION=4.6
        - php: '5.3'
          env: WP_VERSION=4.5

        - php: '5.6'
          env: WP_VERSION=master PHP_LINT=1 WP_PHPCS=1
        - php: '5.6'
          env: WP_VERSION=4.6
        - php: '5.6'
          env: WP_VERSION=4.5

        - php: '7.0'
          env: WP_VERSION=master PHP_LINT=1
        - php: '7.0'
          env: WP_VERSION=4.6
        - php: '7.0'
          env: WP_VERSION=4.5

        - php: 'hhvm'
          env: WP_VERSION=master PHP_LINT=1

    allow_failures:
        - php: 'hhvm'

before_script:
    - export WP_TESTS_DIR=/tmp/wordpress/tests/phpunit
    - export WP_CORE_DIR=/tmp/wordpress/src/
    - git clone --depth=50 --branch="$WP_VERSION" git://develop.git.wordpress.org/ /tmp/wordpress
    - mysql -e "CREATE DATABASE wordpress_tests;" -uroot
    - cp /tmp/wordpress/wp-tests-config-sample.php /tmp/wordpress/wp-tests-config.php
    - sed -i "s/youremptytestdbnamehere/wordpress_tests/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourusernamehere/travis/" /tmp/wordpress/wp-tests-config.php
    - sed -i "s/yourpasswordhere//" /tmp/wordpress/wp-tests-config.php
    - |
      if [[ "$WP_PHPCS" == "1" ]]; then
          git clone --depth=1 https://github.com/squizlabs/PHP_CodeSniffer.git /tmp/php-codesniffer
          git clone --depth=1 https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git --branch master /tmp/wordpress-coding-standards
          /tmp/php-codesniffer/scripts/phpcs --config-set installed_paths /tmp/wordpress-coding-standards
          phpenv rehash
      fi

script:
    - if [[ "$PHP_LINT" == "1" ]]; then find . -type "f" -iname "*.php" | xargs -L "1" php -l; fi
    - if [[ "$WP_PHPCS" == "1" ]]; then /tmp/php-codesniffer/scripts/phpcs -p -s -v -n --standard=./phpcs.ruleset.xml; fi
    - export WP_MULTISITE=0 && phpunit
    - export WP_MULTISITE=0 && phpunit --group ajax
    - export WP_MULTISITE=1 && phpunit
    - export WP_MULTISITE=1 && phpunit --group ajax

notifications:
    email: false
